server:
  port: 9530
spring:
  application:
    name: ${artifactId}
  #数据源配置
  datasource:
    url: ${eladmin.datasource.url}
    username: ${eladmin.datasource.username}
    password: ${eladmin.datasource.password}