#Swagger属性配置
eladmin:
  swagger:
    enable: false
    title: ElAdminCLoud文档管理中心
    description: ElAdminCLoud文档管理
    license: Powered by ElAdminCLoud
    service-url: https://www.com.google.com
    contact-name: iris
    contact-url: https://www.com.google.com/#/docs
    contact-email: ruixijiejie@gmail.com
# knife4j配置
knife4j:
  enable: ${eladmin.swagger.enable}
  # 开启生产环境屏蔽
  production: false
  setting:
    # 是否不显示Knife4j默认的footer，默认为true(显示)
    enableFooter: false
    # 是否自定义Footer，默认为false(非自定义)
    enableFooterCustom: true
    # 自定义Footer内容,支持Markdown语法
    footerCustomContent: Apache License 2.0 | Copyright baixp  2022
    enableHomeCustom: true
    homeCustomLocation: classpath:eladmin-swagger.md
# 默认路径匹配策略切换回ant_path_matcher
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher