server:
  port: 10086
spring:
  application:
    name: @artifactId@
  #数据源配置
  datasource:
    url: ${eladmin.datasource.url}
    username: ${eladmin.datasource.username}
    password: ${eladmin.datasource.password}

provider:
  application:
    name: eladmin-system

justauth:
  enabled: true
  type:
    github:
      client-id: 75a51afd3b0a2fc32952
      client-secret: dcf425ac89******************736d2317b
      redirect-uri: http://localhost:10001/mate-uaa/auth/callback/github
    wechat_open:
      client-id: wxdcb******4ff4
      client-secret: b4e9dc************************a08ed6d
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/wechat/callback
    QQ:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: http://oauth.xkcoding.com/demo/oauth/qq/callback
      union-id: false
  cache:
    type: redis
    prefix: 'SOCIAL::STATE::'
    timeout: 1h
social:
  vue:
    url: http://localhost:9528/#/socialcallback
## 配置日志显示在spring boot admin
logging:
  file:
    name: logs/app/mate-uaa/mate-uaa.log